version: '3.8'
services:
  frontend:
    image: justinding765/webtoon_translator:frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - WATCHPACK_POLLING=true


  backend:
    image: justinding765/webtoon_translator:backend
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:/usr/src/app/frontend  # Bind mount for backend to access frontend files  
      - ./backend:/usr/src/app/backend
      - /usr/src/app/backend/venv   # Might have do the same with the gomod dependcies. Anonymous volume for the server binary
    environment:
      - WATCHPACK_POLLING=true


